### ISSUE TITLE
Use forms.BleachField when models.BleachField is used

### ISSUE THREAD

**Issue by osamak** [marksweb/django-bleach#13]
When defining a model field using `models.BleachField`, it won't automatically reflect on the ModelForm field.  Instead, the form field has to be defined separately using `forms.BleachField`.  I found this confusing initially given Django's "don't repeat yourself" style.

This can be solved by defining a `formfield` method in the `models.BleachField` class ([documentation](https://docs.djangoproject.com/en/2.2/howto/custom-model-fields/#specifying-form-field-for-model-field)).

Is there a reason why things are the way they are?  If you are you happy with this change, I will submit a pull request.

**Comment by marksweb** [comment]
Hi, that certainly makes sense. Happy for a PR.

As for a reason, I've not really considered it since I took over the project.
