### ISSUE TITLE
Release 0.5.0 has no entry in CHANGELOG

### ISSUE THREAD

**Issue by dyve** [marksweb/django-bleach#5]
**Describe the bug**
In CHANGELOG.md, there is no mention of release 0.5.0 that was just published.

**To Reproduce**
1. View CHANGELOG.md
2. See that there is no mention of 0.5.0

**Expected behavior**
Explanation of what changed in 0.5.0 in CHANGELOG.md

**Comment by marksweb** [comment]
Ah yes, sorry about that. I'll push a `0.5.1` with a note about 0.5 bringing in `ALLOWED_PROTOCOLS`.

**Comment by marksweb** [comment]
Published version `0.5.1`
