### ISSUE TITLE
BleachField form field tries to clean None values

### ISSUE THREAD

**Issue by MrkGrgsn** [marksweb/django-bleach#6]
**Describe the bug**
If the `BleachField.to_python()` is passed a value of `None` it passes this straight to `bleach.clean()` which doesn't accept `None` since 2.1 ([ref](https://github.com/mozilla/bleach/blob/master/CHANGES#L239-L240)) and raises a `TypeError`.

**To Reproduce**
Using Python 2.7.12, Django 1.11.20 and django_bleach 0.5.1.

1. Get a form that contains a BleachField
2. Use the browser's dev tools to delete the textarea for the BleachField
3. Submit the form

**Expected behavior**
`BleachField.to_python()` returns `self.empty_value` if value is `None`. This would be consistent with Django's `CharField` ([code](https://github.com/django/django/blob/master/django/forms/fields.py#L227-L228)).

**Comment by MrkGrgsn** [comment]
It's an edge case (unless I'm missing some requirement for handling `None` values) but I've got an application with a number of tests that rely on BleachField being able to handle them. Would you be happy to accept a PR?

**Comment by marksweb** [comment]
@MrkGrgsn Hi, yeah always happy for contributions. I've not come across this but that might be because I haven't written a test case for it.

**Comment by MrkGrgsn** [comment]
@marksweb It turns out there is a test in [test_forms.py](https://github.com/marksweb/django-bleach/blob/master/django_bleach/tests/test_forms.py#L9-L13) but it's checking that bleach returns the `TypeError` for empty data, which looks wrong to me, or, at least, not following Django convention.

Stand by for a PR.
