### ISSUE TITLE
Allow tag filtering

### ISSUE THREAD

**Issue by DatDerpyDude81** [marksweb/django-bleach#69]
Please add a way to filter only a select few HTML tags. I want to use this to filter out only script tags and I end up having to list out every HTML tag except the script tag.

**Comment by marksweb** [comment]
I'm afraid that's not how bleach works.

They do "allowed" rather than "not allowed"

https://bleach.readthedocs.io/en/latest/clean.html

You'd need to raise a feature request with bleach for this.
